package 左神.ContributionBooster;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Random;

/**
 * 一键自动提交程序
 * 自动生成代码、修改文件、提交到Git
 */
public class AutoCommit {
    
    private static final Random random = new Random();
    private static final String[] COMMIT_MESSAGES = {
        "feat: 添加新功能",
        "fix: 修复bug", 
        "docs: 更新文档",
        "style: 代码格式调整",
        "refactor: 重构代码",
        "test: 添加测试用例",
        "chore: 日常维护",
        "perf: 性能优化",
        "ci: 持续集成配置",
        "build: 构建系统更新"
    };
    
    public static void main(String[] args) {
        System.out.println("=== 一键自动提交程序 ===");
        
        try {
            // 1. 生成随机代码
            generateRandomCode();
            
            // 2. 更新现有文件
            updateExistingFiles();
            
            // 3. 创建新文件
            createNewFiles();
            
            // 4. 更新README
            updateReadme();
            
            // 5. 生成提交信息
            String commitMessage = generateCommitMessage();
            
            System.out.println("=== 操作完成 ===");
            System.out.println("提交信息: " + commitMessage);
            System.out.println("请执行以下命令提交:");
            System.out.println("git add .");
            System.out.println("git commit -m \"" + commitMessage + "\"");
            System.out.println("git push");
            
        } catch (Exception e) {
            System.err.println("操作失败: " + e.getMessage());
            e.printStackTrace();
        }
    }
    
    private static void generateRandomCode() throws IOException {
        System.out.println("1. 生成随机代码...");
        
        // 生成随机类
        String className = "AutoGenerated" + random.nextInt(1000);
        String fileName = "src/左神.ContributionBooster/" + className + ".java";
        
        FileWriter writer = new FileWriter(fileName);
        writer.write("package 左神.ContributionBooster;\n\n");
        writer.write("/**\n");
        writer.write(" * 自动生成的类\n");
        writer.write(" * 生成时间: " + LocalDate.now() + "\n");
        writer.write(" */\n");
        writer.write("public class " + className + " {\n");
        writer.write("    private int id = " + random.nextInt(1000) + ";\n");
        writer.write("    private 左神.String name = \"" + className.toLowerCase() + "\";\n\n");
        writer.write("    public void process() {\n");
        writer.write("        // 处理逻辑\n");
        writer.write("        System.out.println(\"处理ID: \" + id);\n");
        writer.write("    }\n");
        writer.write("}\n");
        writer.close();
        
        System.out.println("   创建文件: " + fileName);
    }
    
    private static void updateExistingFiles() throws IOException {
        System.out.println("2. 更新现有文件...");
        
        // 更新DailyCommit.java
        updateFileWithComment("src/左神.ContributionBooster/DailyCommit.java",
            "// 自动更新: " + LocalDate.now() + " - 版本 " + random.nextInt(100));
        
        // 更新RandomCode.java
        updateFileWithComment("src/左神.ContributionBooster/RandomCode.java",
            "// 自动更新: " + LocalDate.now() + " - 优化 " + random.nextInt(50));
        
        // 更新CommitHelper.java
        updateFileWithComment("src/左神.ContributionBooster/CommitHelper.java",
            "// 自动更新: " + LocalDate.now() + " - 增强 " + random.nextInt(30));
    }
    
    private static void updateFileWithComment(String filePath, String comment) throws IOException {
        File file = new File(filePath);
        if (file.exists()) {
            // 在文件末尾添加注释
            FileWriter writer = new FileWriter(file, true);
            writer.write("\n" + comment + "\n");
            writer.close();
            System.out.println("   更新文件: " + filePath);
        }
    }
    
    private static void createNewFiles() throws IOException {
        System.out.println("3. 创建新文件...");
        
        // 创建配置文件
        String configFile = "src/左神.ContributionBooster/config_" + random.nextInt(100) + ".txt";
        FileWriter configWriter = new FileWriter(configFile);
        configWriter.write("# 自动生成的配置文件\n");
        configWriter.write("version=" + random.nextInt(10) + "." + random.nextInt(10) + "." + random.nextInt(10) + "\n");
        configWriter.write("timestamp=" + System.currentTimeMillis() + "\n");
        configWriter.write("random_value=" + random.nextInt(1000) + "\n");
        configWriter.close();
        
        System.out.println("   创建配置文件: " + configFile);
        
        // 创建日志文件
        String logFile = "src/左神.ContributionBooster/log_" + LocalDate.now().format(DateTimeFormatter.ofPattern("yyyyMMdd")) + ".txt";
        FileWriter logWriter = new FileWriter(logFile, true);
        logWriter.write(LocalDate.now() + " " + LocalDate.now().atStartOfDay().plusSeconds(System.currentTimeMillis() / 1000) + " - 自动更新\n");
        logWriter.close();
        
        System.out.println("   更新日志文件: " + logFile);
    }
    
    private static void updateReadme() throws IOException {
        System.out.println("4. 更新README...");
        
        File readmeFile = new File("src/左神.ContributionBooster/README.md");
        if (readmeFile.exists()) {
            FileWriter writer = new FileWriter(readmeFile, true);
            writer.write("\n## 自动更新记录\n");
            writer.write("- " + LocalDate.now() + ": 自动更新，添加新功能\n");
            writer.write("- 生成时间: " + System.currentTimeMillis() + "\n");
            writer.write("- 随机种子: " + random.nextInt(10000) + "\n");
            writer.close();
            
            System.out.println("   更新README.md");
        }
    }
    
    private static String generateCommitMessage() {
        String baseMessage = COMMIT_MESSAGES[random.nextInt(COMMIT_MESSAGES.length)];
        String timestamp = LocalDate.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        return baseMessage + " - " + timestamp + " #" + random.nextInt(1000);
    }
    
    /**
     * 批量生成多个提交
     */
    public static void batchCommit(int count) {
        System.out.println("=== 批量提交 " + count + " 次 ===");
        
        for (int i = 0; i < count; i++) {
            try {
                System.out.println("\n--- 第 " + (i + 1) + " 次提交 ---");
                
                // 生成随机代码
                generateRandomCode();
                
                // 更新文件
                updateExistingFiles();
                
                // 生成提交信息
                String commitMessage = generateCommitMessage();
                
                System.out.println("提交信息: " + commitMessage);
                System.out.println("请执行: git add . && git commit -m \"" + commitMessage + "\" && git push");
                
                // 等待一秒
                Thread.sleep(1000);
                
            } catch (Exception e) {
                System.err.println("第 " + (i + 1) + " 次提交失败: " + e.getMessage());
            }
        }
        
        System.out.println("\n=== 批量提交完成 ===");
    }
} 